server:
  port: 8762
spring:
  profiles:
    active: git
  application:
    name: config-server
  cloud:
    config:
      override-system-properties: false
      server:
        git:
          uri: https://github.com/renatomateusx/spring-cloud-config.git
          clone-on-start: true
          search-paths:
            config-server/src/main/resources/config/,
            config-server/src/main/resources/config/client-config-first,
            config-server/src/main/resources/config/client-discovery-first
          username: xxx
          password: yyy